# These are supported funding model platforms

github: # obeddhino
patreon: # nike
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: #  cloud-foundry
liberapay: # obeddhino
issuehunt: # obeddhino
lfx_crowdfunding: #  cloud-foundry
polar: # obeddhino
buy_me_a_coffee: #  Buy Me a Coffee obeddhino
thanks_dev: # Replace with a single thanks.dev username
custom: #sponsorship
https://github.com/zhaks/hackathon-sponsorship.git
